document.addEventListener('DOMContentLoaded', () => {
    // Netlify CMS Integration
    const impactCardsContainer = document.getElementById('impact-cards-container');

    // In a real project, you would fetch this data from a file generated by Netlify CMS
    const sampleData = [
        { title: 'Education for All', funded: 62, supporters: 156, goal: 25000, current: 15420 },
        { title: 'Community Food Programs', funded: 58, supporters: 89, goal: 15000, current: 8750 }
    ];

    // Replace your existing function with this one
function renderImpactCards(data) {
    if (impactCardsContainer) {
        impactCardsContainer.innerHTML = data.map(item => `
            <div class="card">
                <h3>${item.title}</h3>
                <p>${item.supporters} supporters • ${item.funded}% funded</p>
                <progress value="${item.current}" max="${item.goal}"></progress>
                
                <!-- THIS IS THE ONLY PRICE LINE WE NEED -->
                <p>₹${item.current.toLocaleString('en-IN')} of ₹${item.goal.toLocaleString('en-IN')}</p>

            </div>
        `).join('');
    }
}

    renderImpactCards(sampleData);


    // Razorpay Integration
    // --- Code to Add: Link amount buttons to the input field ---
const amountButtons = document.querySelectorAll('.amount-btn');
const customAmountInput = document.getElementById('custom-amount');

amountButtons.forEach(button => {
    button.addEventListener('click', () => {
        const amount = button.getAttribute('data-amount');
        customAmountInput.value = amount;
    });
});
// --- End of Code to Add ---

// This line should already be in your file
const donateBtn = document.getElementById('donate-btn');
   

    donateBtn.addEventListener('click', (e) => {
        e.preventDefault();
       const amount = customAmountInput.value;
        const options = {
            "key": "rzp_test_R97BJt5cOtiIX8",
            "amount": amount * 100, // Amount in the smallest currency unit
            "currency": "INR",
            "name": "Social Good Initiative",
            "description": "Donation",
            "handler": function (response){
                // After successful donation
                alert('Thank you for your donation!');
                // Here you would call your serverless function to trigger the Gemini API and send the email
            },
            "prefill": {
                "name": document.getElementById('full-name').value,
                "email": document.getElementById('email').value
            }
        };
        const rzp1 = new Razorpay(options);
        rzp1.open();
    });
});