# This is the backend configuration
backend:
  name: git-gateway
  branch: main

# This is for media (image) uploads
media_folder: "images/uploads"
public_folder: "/images/uploads"

# This defines your content types
collections:
  - name: "programs"
    label: "Donation Programs"
    folder: "_data/programs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Supporters", name: "supporters", widget: "number"}
      - {label: "Percentage Funded", name: "funded", widget: "number"}
      - {label: "Goal Amount", name: "goal", widget: "number"}
      - {label: "Current Amount", name: "current", widget: "number"}